@extends('base')
@section('contenedor')
    @include('snippets.navbar')
    @include('snippets.header')
    @include('snippets.propuesta_valor')
    @include('snippets.frase')
    @include('snippets.servicios')
    @include('snippets.diferencias')
@endsection
